const TIMEDO = 1800;
const NUMBERQUESTION = 20;
const NAME_DB_EXAM = "Exams";
const NAME_DB_CHOICEQUESTION_EXAM = "ChoiceQuestionExam";
const NAME_DB_FILLQUESTION_EXAM = "FillQuestionExam";
const NAME_DB_INFOEXAMUSER = "InfoExamUsers";
const NAME_DB_USERS = "Users";
const NUMBER_EXAM = 3;
const NAME_EXAM = 'Exam';
const NAME_MATH_EXAM = 'math';
const NAME_VN_EXAM = 'vietnamese';
const POINT_BASE = 20;
const TYPE_CHOICE_QUESTION = 'choice';
const TYPE_FILL_QUESTION = 'fill';
const CHECK_TRUE = 'true';
const CHECK_FALSE = 'false';
const FORMAT_DATE = 'MM_YYYY';
const NUMBER_TOP_STUDENT = '5';
module.exports= {
    TIMEDO,
    NUMBERQUESTION,
    NAME_DB_EXAM,
    NAME_DB_CHOICEQUESTION_EXAM,
    NAME_DB_FILLQUESTION_EXAM,
    NAME_DB_INFOEXAMUSER,
    NAME_DB_USERS,
    NUMBER_EXAM,
    NAME_MATH_EXAM,
    NAME_VN_EXAM,
    POINT_BASE,
    TYPE_CHOICE_QUESTION,
    TYPE_FILL_QUESTION,
    CHECK_TRUE,
    CHECK_FALSE,
    FORMAT_DATE,
    NUMBER_TOP_STUDENT,
    NAME_EXAM
}
