swagger: "2.0"
info:
  version: "0.0.1"
  title: Exercise Service
# during dev, should point to your local machine
host: 127.0.0.1:8004
# basePath prefixes all resource paths 
basePath: /api/exercise
# 
securityDefinitions:
  auth0:
    type: apiKey
    name: Authorization
    in: header
    description: "Authorization logged to application"
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /topic/{topicId}/number_question:
    x-swagger-router-controller: question
    get:
      description: Returns list questions of topic
      operationId: getListQuestionsOfTopic
      parameters:
        - name: topicId
          in: path
          description: id of topic
          required: true
          type: string
        - name: numberQuestion
          in: query
          description: number question wanted get
          required: true
          type: integer
        
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListQuestionOfTopic"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /choice_question:
    x-swagger-router-controller: question
    post:
      description: insert choice question of Topic
      operationId: insertChoiceQuestionIntoTopic
      parameters:
        - name: body
          in: body
          description: fields of question
          schema:
            $ref: "#/definitions/ChoiceQuestionRequest"           
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    put:
      description: "update choice question of topic"
      operationId: updateChoiceQuestionOfTopic
      parameters:
        - name: body
          in: body
          description: fields of question
          schema:
            $ref: "#/definitions/ChoiceQuestionUpdateRequest"  
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /fill_question:
    x-swagger-router-controller: question
    post:
      description: insert fill question of Topic
      operationId: insertFillQuestionIntoTopic
      parameters:
        - name: body
          in: body
          description: fields of question
          schema:
            $ref: "#/definitions/FillQuestionRequest"           
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    put:
      description: "update question of topic"
      operationId: updateFillQuestionOfTopic
      parameters:
        - name: body
          in: body
          description: fields of question
          schema:
            $ref: "#/definitions/FillQuestionUpdateRequest"  
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
            
  /answer/{session}/{questionId}:
    x-swagger-router-controller: question
    post:
      description: verify answer
      operationId: verifyAnswer
      parameters:
        - name: questionId
          in: path
          description: id of question
          required: true
          type: string
        - name: session
          in: path
          description: session of do exercise
          required: true
          type: string
        - name: body
          in: body
          description: fields of question
          schema:
            $ref: "#/definitions/AnswerRequest"           
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AnswerResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /result_exercise/{session}:
    x-swagger-router-controller: question
    get:
      description: Returns result exercise of topic
      operationId: getResultExerciseOfTopic
      parameters:
        - name: session
          in: path
          description: session of do exercise
          required: true
          type: string
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ResultExercise"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /remove_allsession:
    x-swagger-router-controller: question
    post:
      description: remove all session
      operationId: removeAllSession
      parameters:
        - name: body
          in: body
          description: list session
          schema:
            $ref: "#/definitions/ListSession"           
      security:
      - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  ListQuestionOfTopic:
    type: object
    properties:
      session:
        type: string
        description: session of get list question 
      listQuestions:
        type: array
        items:
          type: object
          description: if choice question, object have properties (_id, content, answer (ansA, ansB, ansC, ansD), type = 'choice'). if fill question, object have properties (_id, content, type = 'fill')

  # ChoiceQuestionResponse:
  #   type: object
  #   properties:
  #     _id:
  #       type: string
  #     content:
  #       type: string
  #     answers:
  #       type: object
  #       properties:
  #         ansA:
  #           type: string
  #         ansB:
  #           type: string
  #         ansC:
  #           type: string
  #         ansD:
  #           type: string
            
  # FillQuestionResponse:
  #   type: object
  #   properties:
  #     _id:
  #       type: string
  #     content:
  #       type: string
  
  ChoiceQuestionRequest:
    type: object
    properties:
      topicId:
        type: string
      content:
        type: string
      answers:
        type: object
        properties:
          ansA:
            type: string
          ansB:
            type: string
          ansC:
            type: string
          ansD:
            type: string
      answerRight:
        type: string
      explainRight:
        type: string
      suggest:
        type: string
  
  ChoiceQuestionUpdateRequest:
    type: object
    properties:
      topicId:
        type: string
      id:
        type: string
      content:
        type: string
      answers:
        type: object
        properties:
          ansA:
            type: string
          ansB:
            type: string
          ansC:
            type: string
          ansD:
            type: string
      answerRight:
        type: string
      explainRight:
        type: string
      suggest:
        type: string
  
  FillQuestionRequest:
    type: object
    properties:
      topicId:
        type: string
      content:
        type: string
      answerRight:
        type: string
      explainRight:
        type: string
      suggest:
        type: string
        
  FillQuestionUpdateRequest:
    type: object
    properties:
      topicId:
        type: string
      id:
        type: string
      content:
        type: string
      answerRight:
        type: string
      explainRight:
        type: string
      suggest:
        type: string
  ResultExercise:
    type: object
    required:
      - point
    properties:
      numberQuestion:
        type: integer
      numberAnswerRight:
        type: integer
      point:
        type: integer
  MessageResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        
  AnswerRequest:
    type: object
    required:
      - answer
    properties:
      typeQuestion:
        description: choice or fill
        type: string
      answer:
        description: if choice question, answer ansA, ansB, ansC, ansD. if fill answer, answer any thing
        type: string
        
  AnswerResponse:
    type: object
    required:
      - result
    properties:
      result:
        type: boolean
      record:
        type: string
  ListSession:
    type: object
    properties:
      listSession:
        description: list session
        type: array
        items:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
