swagger: "2.0"
info:
  version: "0.0.1"
  title: Chat Service
# during dev, should point to your local machine
host: 103.114.107.16:8002
# host: 127.0.0.1:8002
# basePath prefixes all resource paths 
basePath: /api/chat
#
securityDefinitions:
  auth0:
    type: apiKey
    name: Authorization
    in: header
    description: "Authorization logged to application"
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /all_message/{idChannel}:
    x-swagger-router-controller: message
    get:
      description: return all message of user
      # used as the method name of the controller
      operationId: getAllMessageInChannel
      parameters:
        - name: idChannel
          in: path
          description: id channel
          required: true
          type: string
      security:
        - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AllMessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /all_info_channel:
    x-swagger-router-controller: message
    get:
      description: return all info channel 
      # used as the method name of the controller
      operationId: getAllInfoChannel
      # security:
      #   - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AllInfoChannelResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  AllMessageResponse:
    type: object
    properties:
      listMessages:
        description: list message
        type: array
        items:
          $ref: "#/definitions/ItemMessage"
  ItemMessage:
    type: object
    properties:
      _id:
        description: id message
        type: string
      create:
        description: time chat with admin. Vd:19:15 12/12/2018
        type: string
      data:
        description: content chat
        type: string
      idSender:
        description: message of me?
        type: string
      idChannel:
        description: id of channel
        type: string
  AllInfoChannelResponse:
    type: object
    properties:
      listInfoChannel:
        description: list info channel
        type: array
        items:
          $ref: "#/definitions/ItemInfoChannel"
  ItemInfoChannel:
    type: object
    properties:
      _id:
        description: id object
        type: string
      idChannel:
        description: id channel
        type: string
      lastMessage:
        description: last message of channel
        type: string
      numberMessageWait:
        description: number message wait
        type: integer
      
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
