swagger: "2.0"
info:
  version: "0.0.1"
  title: Chat Service
# during dev, should point to your local machine
host: localhost:8002
# basePath prefixes all resource paths 
basePath: /api/chat
#
securityDefinitions:
  auth0:
    type: apiKey
    name: Authorization
    in: header
    description: "Authorization logged to application"
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /all_message:
    x-swagger-router-controller: message
    get:
      description: return all message of user
      # used as the method name of the controller
      operationId: getAllMessage
      # security:
      #   - auth0: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/AllMessageResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  AllMessageResponse:
    type: object
    properties:
      listMessage:
        description: list message
        type: array
        items:
          $ref: "#/definitions/ItemMessage"
  ItemMessage:
    type: object
    properties:
      _id:
        description: id message
        type: string
      timeChat:
        description: time chat with admin. Vd:19:15 12/12/2018
        type: string
      content:
        description: content chat
        type: string
      isMe:
        description: message of me?
        type: boolean
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
